mysql:

  database: 'minecraft'

  address: 127.0.0.1
  port: 3306

  username: root
  password: ''

rabbitmq:
  enabled: false # Set to true to use web interface!

  address: 127.0.0.1
  port: 6379

  user: guest
  password: 'guest'