name: PermiPlus
description: 'An efficient permissions plugin with groups!'
version: '${project.version}'
main: dev.grcq.permiplus.PermiPlus
authors: [grcq]
website: https://grcq.dev/
depend: [PriveAPI]
